resource_labels = { "provider" : "jx" }
jx_git_url = "https://github.com/aurumsoftware/jx3-gke-cluster"
gcp_project = "aurum-services"
gsm = true
cluster_location = "us-east1-b"
cluster_name = "services-v1"
lets_encrypt_production = false
tls_email = "devops@aurum.com.br"
jenkins_x_namespace = "jx"