resource_labels = { "provider" : "jx" }
jx_git_url = "https://github.com/aurumsoftware/jx3-gke-cluster"
gcp_project = "aurum-services"
gsm = true
cluster_location = "us-east1-b"
cluster_name = "jenkins-x-v1"
lets_encrypt_production = false
tls_email = "devops@aurum.com.br"
apex_domain = "aurum.com.br"
subdomain = "-jx"
jenkins_x_namespace = "jx"
min_node_count = 1
max_node_count = 5
node_machine_type = "n1-standard-4"